name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4    
   
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore TicketDashboard.sln

    - name: Build solution
      run: dotnet build TicketDashboard.sln --configuration Release --no-restore 

    - name: Run tests 
      run: dotnet test TicketDashboard.sln --configuration Release --no-build 

    - name: Publish API
      run: dotnet publish TicketDashboard.Api/TicketDashboard.Api.csproj --configuration Release --output ./publish --no-build  

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with: 
        name: TicketDashboard-Api
        path:  ./publish